/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as ProjektyRouteImport } from './routes/projekty'
import { Route as PolitykaPrywatnosciRouteImport } from './routes/polityka-prywatnosci'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'

const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjektyRoute = ProjektyRouteImport.update({
  id: '/projekty',
  path: '/projekty',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitykaPrywatnosciRoute = PolitykaPrywatnosciRouteImport.update({
  id: '/polityka-prywatnosci',
  path: '/polityka-prywatnosci',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/projekty': typeof ProjektyRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/projekty': typeof ProjektyRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/polityka-prywatnosci': typeof PolitykaPrywatnosciRoute
  '/projekty': typeof ProjektyRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/polityka-prywatnosci'
    | '/projekty'
    | '/regulamin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/polityka-prywatnosci' | '/projekty' | '/regulamin'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/polityka-prywatnosci'
    | '/projekty'
    | '/regulamin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  PolitykaPrywatnosciRoute: typeof PolitykaPrywatnosciRoute
  ProjektyRoute: typeof ProjektyRoute
  RegulaminRoute: typeof RegulaminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projekty': {
      id: '/projekty'
      path: '/projekty'
      fullPath: '/projekty'
      preLoaderRoute: typeof ProjektyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polityka-prywatnosci': {
      id: '/polityka-prywatnosci'
      path: '/polityka-prywatnosci'
      fullPath: '/polityka-prywatnosci'
      preLoaderRoute: typeof PolitykaPrywatnosciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  PolitykaPrywatnosciRoute: PolitykaPrywatnosciRoute,
  ProjektyRoute: ProjektyRoute,
  RegulaminRoute: RegulaminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
